from pathlib import Path

from numba import (
    njit as njit,
    prange as prange,
)
import numpy as np
from _typeshed import Incomplete
from numpy.typing import NDArray as NDArray

_supported_systems: Incomplete
_supported_sessions: Incomplete

def _process_frame_message_batch(log_path: Path, file_names: list[str], onset_us: np.uint64) -> list[np.uint64]:
    """Processes the target batch of VideoSystem-generated messages stored in the .npz log file.

    This worker function is used by the _extract_camera_timestamps() function to process multiple message batches in
    parallel to speed up the overall camera timestamp data processing.

    Args:
        log_path: The path to the processed .npz log file.
        file_names: The names of the individual message .npy files stored in the target archive.
        onset_us: The onset of the frame data acquisition, in microseconds elapsed since UTC epoch onset.

    Returns:
        The list of frame acquisition timestamps for all frames whose messages have been processed as part of the
        batch, stored as microseconds since UTC epoch onset.
    """

def _extract_camera_timestamps(log_path: Path, n_workers: int = -1) -> tuple[np.uint64, ...]:
    """Extracts the video camera frame acquisition timestamps from the target .npz log file generated by a VideoSystem
    instance during sl-experiment runtime.

    This worker function was copied from the ataraxis-video-system library and optimized to use multiprocessing to
    achieve a measurable speedup while processing large log files.

    Notes:
        If the target .npz archive contains fewer than 2000 messages, the processing is carried out sequentially
        regardless of the specified worker-count.

    Args:
        log_path: The path to the .npz log file that stores the logged data generated by the VideoSystem
            instance during runtime.
        n_workers: The number of parallel worker processes (CPU cores) to use for processing. Setting this to a value
            below 1 uses all available CPU cores. Setting this to a value of 1 conducts the processing sequentially.

    Returns:
        A tuple that stores the frame acquisition timestamps. Each timestamp is stored as the number of microseconds
        since the UTC epoch onset.

    Raises:
        ValueError: If the target .npz archive does not exist.
    """

def process_camera_timestamps(
    session_path: Path,
    log_id: int,
    manager_id: int,
    job_count: int,
    reset_tracker: bool = False,
    processed_data_root: Path | None = None,
    workers: int = -1,
) -> None:
    """Reads the specified camera log .npz file and extracts the frame acquisition timestamps as an uncompressed
    .feather file.

    This function is used to process the log archives generated by any video camera used in the Sun lab. It assumes that
    the data was logged using the assets from the ataraxis-video-system library.

    Args:
        session_path: The path to the session directory for which to process the camera log file.
        log_id: The name (ID) of the log archive to process, e.g. '51'.
        manager_id: The unique identifier of the manager process that manages the log processing runtime.
        job_count: The total number of jobs executed as part of the behavior processing pipeline that calls this
            function.
        reset_tracker: Determines whether to reset the tracker file before executing the runtime. This allows
            recovering from deadlocked runtimes, but otherwise should not be used to ensure runtime safety.
        processed_data_root: The absolute path to the directory where processed data from all projects is stored, if
            different from the root directory provided as part of the 'session_path' argument.
        workers: The number of worker processes to use for extracting the camera frame timestamps in parallel. Setting
            this argument to a value less than 1 uses all available CPU cores. Setting this to a value of 1 conducts
            the processing sequentially.
    """
