"""Provides assets for extracting camera frame acquisition timestamps from .npz log archives generated by behavior video
cameras used in the Sun lab.
"""

from enum import IntEnum
from pathlib import Path  # noqa: TC003

import polars as pl
from sl_shared_assets import SessionData
from ataraxis_video_system import extract_logged_camera_timestamps
from ataraxis_base_utilities import LogLevel, console


class CameraLogIds(IntEnum):
    """Defines the log file identifiers for behavior video cameras used by the Mesoscope-VR system."""

    FACE = 51
    """The log file identifier for the face camera."""
    BODY = 62
    """The log file identifier for the body camera."""


CAMERA_OUTPUT_NAMES: dict[int, str] = {
    CameraLogIds.FACE: "face_camera_timestamps",
    CameraLogIds.BODY: "body_camera_timestamps",
}
"""Maps supported camera log identifiers to output file names."""


def process_camera_timestamps(
    session_path: Path,
    log_id: int,
    workers: int = -1,
) -> None:
    """Reads the specified camera log .npz file and extracts the frame acquisition timestamps as an uncompressed
    .feather file.

    Processes the log archives generated by Mesoscope-VR video cameras used in the Sun lab. Assumes that the data was
    logged using the assets from the ataraxis-video-system library.

    Args:
        session_path: The path to the session's data directory for which to process the camera log file.
        log_id: The unique identifier of the camera log file to process: 51 (face) or 62 (body).
        workers: The number of worker processes to use for extracting the camera frame timestamps in parallel. Setting
            this argument to a value less than 1 uses all available CPU cores. Setting this to a value of 1 conducts
            the processing sequentially.
    """
    # Loads the target session's data hierarchy into memory.
    session = SessionData.load(session_path=session_path)

    # Resolves the path to the processed log file.
    log_path = session.raw_data.behavior_data_path.joinpath(f"{log_id}_log.npz")

    # Resolves the output path based on the log ID.
    output_name = CAMERA_OUTPUT_NAMES[log_id]
    output_path = session.processed_data.camera_data_path.joinpath(f"{output_name}.feather")

    console.echo(message=f"Extracting video camera frame timestamps from '{log_id}' log file...")

    # Extracts timestamp data from the log archive using the function from ataraxis-video-system.
    timestamp_data = extract_logged_camera_timestamps(log_path=log_path, n_workers=workers)

    # Converts extracted data to Polars series.
    timestamps_series = pl.Series(name="frame_time_us", values=timestamp_data)

    # Saves extracted data using Feather format and no compression to support memory-mapping the file during
    # processing.
    timestamps_series.to_frame().write_ipc(file=output_path, compression="uncompressed")

    console.echo(message="Camera frame timestamp processing: Complete.", level=LogLevel.SUCCESS)
