"""This module provides the Command-Line Interface (CLI) for processing behavior data acquired in the Sun lab."""

from pathlib import Path

import click

from .pipeline import process_session

# Ensures that displayed CLICK help messages are formatted according to the lab standard.
CONTEXT_SETTINGS = {"max_content_width": 120}


@click.command("behavior", context_settings=CONTEXT_SETTINGS)
@click.option(
    "-sp",
    "--session-path",
    type=click.Path(exists=True, file_okay=False, dir_okay=True, path_type=Path),
    required=True,
    help="The absolute path to the session's root data directory to process.",
)
@click.option(
    "-id",
    "--job-id",
    type=str,
    default=None,
    help=(
        "The unique hexadecimal identifier for this processing job. If provided, runs only the matching job "
        "(remote mode)."
    ),
)
@click.option("--runtime", is_flag=True, help="Determines whether to process the session's runtime data.")
@click.option("--face-camera", is_flag=True, help="Determines whether to process the face camera timestamps.")
@click.option("--body-camera", is_flag=True, help="Determines whether to process the body camera timestamps.")
@click.option("--actor", is_flag=True, help="Determines whether to process the Actor microcontroller data.")
@click.option("--sensor", is_flag=True, help="Determines whether to process the Sensor microcontroller data.")
@click.option("--encoder", is_flag=True, help="Determines whether to process the Encoder microcontroller data.")
@click.option(
    "-w",
    "--workers",
    type=int,
    default=-1,
    help="The number of worker processes to use. Set to -1 (default) to use all available CPU cores.",
)
def behavior(
    session_path: Path,
    job_id: str | None,
    *,
    runtime: bool,
    face_camera: bool,
    body_camera: bool,
    actor: bool,
    sensor: bool,
    encoder: bool,
    workers: int,
) -> None:
    """Processes the behavior data stored inside one or more .npz log archives of the target session.

    This command functions as the entry point for processing the data stored in the .npz log archives generated by the
    sl-experiment library during runtime. If no specific job flags or job identifiers are provided, the pipeline
    processes all available log files. If a unique job identifier is provided, the pipeline only executes that
    specific job.
    """
    process_session(
        session_path=session_path,
        job_id=job_id,
        process_runtime=runtime,
        process_face_camera=face_camera,
        process_body_camera=body_camera,
        process_actor_microcontroller=actor,
        process_sensor_microcontroller=sensor,
        process_encoder_microcontroller=encoder,
        workers=workers,
    )
